### ISSUE TITLE
Binary apk for Android 

### ISSUE THREAD

**Issue by ghost** [procrastine-inc/minimalistic-telegram#2]
Hi, sorry for this issue. How can I get the binary of apk for Android? I was looking for minimal non-distracting telegram client and I stumbled upon this awesome project.

Is the development slow or halted?

This is an awesome project. All the Best ☺️👍🏻

**Comment by MetaMmodern** [comment]
Hello @zwuv ! Thank you for the interest. This project is currently frozen and has no ongoing development. It has issues with code quality, UX, bugs and compatibility on web platforms. It's support requires a lot of effort which I don't have spare at the moment. In the long run it is planned to be maybe rewritten into a different tech stack.

I can't provide an .apk cause the project was never "built" properly and I can't promise that I can do that and it will work.

**Comment by vermi4elli** [comment]
@zwuv Although please keep tuned since some work is already planned, we will ping you once the app is ready to be tried out or to be contributed to 😊

**Comment by ghost** [comment]
Thankyou for the replies.
@MetaMmodern Ok I understand you now better. And I appreciate the vision and efforts behind the project. All the best. 😃👍🏻

@vermi4elli Sure, thankyou too. That's a great news. 🎉
